title: "ENG LIM PENJAN ANTONIO (임대한)"
description: "Software developer with 2.5 years of experience spearheading mobile application development across telecom and enterprise sectors, using modern development practices and Kotlin/Java. Experience with AI/ML research enabling development of efficient and scalable applications."
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# SEO
author: "ENG LIM PENJAN ANTONIO"
url: "https://daehan-lim.github.io"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
aux_links:
  "LinkedIn":
    - "https://linkedin.com/in/penjan-a-eng-lim"
  "GitHub":
    - "https://github.com/daehan-lim"

search_enabled: false
heading_anchors: true